
development:
 adapter: postgresql
 encoding: unicode
 database: chatbot_development
 pool: 16
 username: postgres
 password: postgres

test:
 adapter: postgresql
 encoding: unicode
 database: chatbot_test
 pool: 16
 username: postgres
 password: postgres
