
development:
 adapter: postgresql
 encoding: unicode
 database: fourtyonestudio_development
 pool: 16
 username: postgres
 password: postgres
 
test:
 adapter: postgresql
 encoding: unicode
 database: fourtyonestudio_test
 pool: 16
 username: postgres
 password: postgres
